import type {Metadata} from "next";

import {Inter} from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Card Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} m-auto grid min-h-screen max-w-screen-xl grid-rows-[auto,1fr,auto]`}
      >
        <header className="flex pt-5">
          <Link className="" href="/">
            <h1 className="border-b-4 border-b-slate-500 p-2 text-2xl transition-colors hover:bg-slate-500">
              Card Gallery
            </h1>
          </Link>
        </header>
        <main className="mt-5 px-10 pb-5">{children}</main>
        <footer className="text-center leading-[4rem] opacity-70">© 2024, by Kevoff</footer>
      </body>
    </html>
  );
}
